swagger: '2.0'
info:
  description: TDOT Roadway Cameras.
  version: 1.0.0
  title: TDOT Roadway Cameras
  contact:
    email: escofieldpublic@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
basePath: /v1
tags:
- name: ErikScofield
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: 'http://swagger.io'
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: 'http://swagger.io'
schemes:
- http
paths:
  /Camera:
    get:
      tags:
      - Camera
      summary: Get a list of cameras
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Search camera query
        required: false
        schema:
          $ref: '#/definitions/CameraSearch'
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Camera'
        404:
          description: No results found
        405:
          description: Invalid input
  /Camera/Routes:
    get:
      tags:
      - Camera
      summary: Returns avaliable routes
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: string
  /Camera/Jurisdictions:
    get:
      tags:
      - Camera
      summary: Returns avaliable Jurisdictions
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: string
  /Camera/{id}:
    get:
      tags:
      - Camera
      summary: Get the camera info for this id
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        minimum: 1
        description: Camera ID
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Camera'
        405:
          description: Invalid input          
  /user/favorite:
    put:
      tags:
      - user
      summary: Add camera to favorites
      description: No auth, in memmory state favorites.
      operationId: AddFavorites
      consumes:
      - application/json      
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Created favorite object
        required: true
        schema:
          $ref: '#/definitions/Favorite'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Favorite'
definitions:
  Favorite:
    type: object
    properties:
      id:
        type: string
        format: uuid
      userId:
        type: string
        format: uuid
      name:
        type: string
      url:
        type: string
      camera:
        $ref: '#/definitions/Camera'
    xml:
      name: Order
  CameraSearch:
    type: object
    properties:
      route:
        type: string
      jurisdiction:
        type: string
    xml:
      name: Category
  Camera:
    type: object
    properties:
      id:
        type: integer
        format: int32
      thumbnailUrl:
        type: string
      title:
        type: string
      jurisdiction:
        type: string
      route: 
        type: string
      httpVideoUrl:
        type: string