/*
 * TDOT Roadway Cameras
 *
 * TDOT Roadway Cameras.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: escofieldpublic@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// class Favorite
    /// </summary>
    public class Favorite
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        public Guid? Id { get; set; }
      
        /// <summary>
        /// Gets or Sets favorite title
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Camera
        /// </summary>
        public Camera Camera { get; set; }
    }
}
